### PR TITLE
8316304: (fs) Add support for BasicFileAttributes.creationTime() for Linux

### PR DESCRIPTION
**Pull request by jerboaa**
Please review this nio change which adds `BasicFileAttributes.creationTime()` support for Linux by means of the `statx` Linux specific system call. The patch does a dynamic lookup of the function and if it is available, uses it to set the support birth time capability in `UnixNativeDispatcher`. When `statx` is not available, it won't use it and fall back to the old behaviour on such systems. It should, however, compile fine on Linux systems not supporting the `statx` system call.

Testing:
- [x] GHA (MacOS X failure seems unrelated)
- [x] `java.nio` tests.
- [x] Manual builds and tests on older glibc versions (2.17 => fallback, 2.28+ => works). Compiles fine and falls back to the not supported case as it was before this patch.

Thoughts?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer), 1 [Author](https://openjdk.org/bylaws#author))

### Issue
 * [JDK-8316304](https://bugs.openjdk.org/browse/JDK-8316304): (fs) Add support for BasicFileAttributes.creationTime() for Linux (**Enhancement** - P3)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [ad428030](https://git.openjdk.org/jdk/pull/15792/files/ad428030755d094683f0ac955a937d1e80f8e893)
 * [Alan Bateman](https://openjdk.org/census#alanb) (@AlanBateman - **Reviewer**) ⚠️ Review applies to [cbb24e38](https://git.openjdk.org/jdk/pull/15792/files/cbb24e38c5f0bbeecfa46a05de31b13cb3c937d4)
 * [Brian Burkhalter](https://openjdk.org/census#bpb) (@bplb - **Reviewer**)
 * [Hamlin Li](https://openjdk.org/census#mli) (@Hamlin-Li - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15792/head:pull/15792` \
`$ git checkout pull/15792`

Update a local copy of the PR: \
`$ git checkout pull/15792` \
`$ git pull https://git.openjdk.org/jdk.git pull/15792/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15792`

View PR using the GUI difftool: \
`$ git pr show -t 15792`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15792.diff">https://git.openjdk.org/jdk/pull/15792.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15792#issuecomment-1725643898)

### CODE REVIEW

**Comment by AlanBateman** [comment]
Is statx a complete superset of stat? If so, then the prototype should use it instead of stat, not in addition, meaning there should be one syscall rather than two.

If this goes ahead then I think should look at what it would take to move it src/java.base/linux, meaning the LinuxFileSystemProvider.

**Comment by jerboaa** [comment]
> Is statx a complete superset of stat? If so, then the prototype should use it instead of stat, not in addition, meaning there should be one syscall rather than two.

The reason why I've chosen this one so far is two fold: a) What to do if `statx` is not available? (`glibc < 2.28` and/or `kernel < 4.11`) b) it seems much less risky that way, as we are only changing creationTime reporting. Everything else remains unchanged. Thus, a better fit for backports. a) seems a blocker for older systems, so we would need two separate implementations anyway?

> If this goes ahead then I think should look at what it would take to move it src/java.base/linux, meaning the LinuxFileSystemProvider.

Incidentally, that's what my initial version was using and I've reconsidered going with this one instead since the complexity seemed not worth it. It would need to delegate to `UnixFileAttributes` anyway for older systems and the gist of the patch would be the native parts.

**Comment by AlanBateman** [comment]
> The reason why I've chosen this one so far is two fold: a) What to do if `statx` is not available? (`glibc < 2.28` and/or `kernel < 4.11`) b) it seems much less risky that way, as we are only changing creationTime reporting. Everything else remains unchanged. Thus, a better fit for backports. a) seems a blocker for older systems, so we would need two separate implementations anyway?

The code to use both will be there but when you invoke a method to get the file attributes in bulk then it should get a consistent view with one syscall.  Backports are not a concern here.

> Incidentally, that's what my initial version was using and I've reconsidered going with this one instead since the complexity seemed not worth it. It would need to delegate to `UnixFileAttributes` anyway for older systems and the gist of the patch would be the native parts.

I think this should be explored, maybe along the lines of BsdFileSystemProvider override getFileAttributeView so that it has a more specific implementation of each of the attribute views.

**Comment by AlanBateman** [comment]
One other thing to try is to rename prepAttributes to something like copyStatAttributes and add a copyStatXAttributes that copies the fields from the statx structure. That on its own go with call stat or statx, never both.

**Comment by jerboaa** [comment]
> One other thing to try is to rename prepAttributes to something like copyStatAttributes and add a copyStatXAttributes that copies the fields from the statx structure. That goes with calling stat or statx, never both.

OK. Just to clarify: if `statx` is available it should use it and retrieve all needed attributes from the statx call (if all attributes can be retrieved that way). Otherwise use `stat64/lstat` as before (with birth time missing).

**Comment by AlanBateman** [comment]
> OK. Just to clarify: if `statx` is available it should use it and retrieve all needed attributes from the statx call (if all attributes can be retrieved that way). Otherwise use `stat64/lstat` as before (with birth time missing).

Yes, I think we should think of statx as an extended stat.

**Comment by gnu-andrew** [comment]
Using either `statx` or `stat64` makes sense to me. I can see why you might want the safety of having the other attributes available on a system which thinks it has `statx`, but fails for some reason, but that also makes the situation hard to debug. Do you have no creation time because `statx` is not supported or because it failed? Also, in the proposed patch, the failing `statx` would fail the entire function anyway, so you wouldn't get the other attributes from `stat64` as far as I can see.

Looking at `statx`, the fields pretty much map onto the `stat64` ones with `st_` replaced with `stx_`. The exceptions are `rdev` and `dev` which `statx` provides split into major and minor. The `makedev` function can be used to convert this pair into a `dev_t`. 
We also seem to be missing use of nanoseconds for birthtime. Was this absent on Mac OS? It would be good to make this consistent with a/m/ctime and provide greater accuracy.

Using one or the other seems like it might also reduce some of the duplication here. It is a bit odd to have all attributes initialised in `prepAttributes` but then another adjusted outside that in three different places. Maybe we could instead just wrap `prepAttributes` in a wrapper function which calls `copyStatAttributes` or `copyStatXAttributes` as appropriate?  It seems feasible you could even copy the `statx` fields into a `stat64` buffer and re-use `prepAttributes` as is.

I don't see how moving this to a Linux-specific class would work. Would that not mean a lot of duplication with the `stat64` handling, not to mention some Linux systems may still need to use `stat64`? It's not like there isn't a whole bunch of platform-specific code in the file already and the separate class seems more appropriate for cases where the feature is only available on Linux, not where the feature can be handled slightly differently on some Linux systems.

Could `STATX_POSSIBLY_AVAILABLE` not just be replaced with `defined(__linux__)` for clarity? Or maybe that is part of the intention that `statx` may potentially be available on other platforms in future?

I don't really get the point about backports. According to [the build platform Wiki page](https://wiki.openjdk.org/display/Build/Supported+Build+Platforms), Oracle still build JDK 20 against a OEL 6 or 7 buildroot, which means a `glibc` that doesn't support `statx`. I expect most builds of 22 will be in an environment without `statx`, but plenty will run in one where it is.

**Comment by jerboaa** [comment]
@AlanBateman @gnu-andrew Thanks for your input! Here is an updated patch, now using LinuxFileSystemProvider and the logic to use `statx` is now in the linux specific directory trees. The fallback code is unchanged (using `UnixNativeDispatcher`). This version never uses both `stat64` and `statx`. It only uses `statx` if its available and uses the older `stat64` otherwise. 

On a Linux system that has `statx` (using `LastModified` from the bug):
```
# grep test.txt strace_out.log 
execve("./jdk-22.0.0+0/bin/java", ["./jdk-22.0.0+0/bin/java", "LastModified", "test.txt"], 0xffffe07f0b98 /* 42 vars */) = 0
[pid 17058] statx(AT_FDCWD, "test.txt", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=0, ...}) = 0
# stat test.txt 
  File: test.txt
  Size: 0         	Blocks: 0          IO Block: 65536  regular empty file
Device: fd00h/64768d	Inode: 100734611   Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Context: unconfined_u:object_r:admin_home_t:s0
Access: 2023-09-21 13:14:00.464356794 -0400
Modify: 2000-01-01 01:01:00.000000000 -0500
Change: 2023-09-21 13:17:13.835434277 -0400
 Birth: 2023-09-21 13:12:13.033760507 -0400
```

On a Linux system that doesn't have `statx`:
```
# grep 'stat' strace_out.log  | grep testme
[pid  8302] stat("testme.txt", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
# stat testme.txt 
  File: ‘testme.txt’
  Size: 0         	Blocks: 0          IO Block: 65536  regular empty file
Device: fd00h/64768d	Inode: 100822778   Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Context: unconfined_u:object_r:admin_home_t:s0
Access: 2023-09-21 13:09:46.459640944 -0400
Modify: 2000-01-01 01:01:00.000000000 -0500
Change: 2023-09-21 13:16:08.142395814 -0400
 Birth: -
```
Please let me know what you think!

FWIW, I've compiled this fine on Alpine Linux, so there aren't any glibc guards anymore.

**Comment by AlanBateman** [comment]
> Thanks for your input! Here is an updated patch, now using LinuxFileSystemProvider and the logic to use `statx` is now in the linux specific directory trees. The fallback code is unchanged (using `UnixNativeDispatcher`). This version never uses both `stat64` and `statx`. It only uses `statx` if its available and uses the older `stat64` otherwise.

I was chatting with @bplb about this change, mostly about testing and maintainability. We both agreed that this PR isn't the right place to do the refactoring, there is a lot disruptive changes needed to allow overriding of what is currently in the Unix* code. So if it's okay with you, we think go back the original/smaller change in UnixNativeDispatcher.c but use stat or statx, before both, as you have in the second iteration. Would that be okay with you?

**Comment by jerboaa** [comment]
Sorry for the late reply. I was travelling.

> > Thanks for your input! Here is an updated patch, now using LinuxFileSystemProvider and the logic to use `statx` is now in the linux specific directory trees. The fallback code is unchanged (using `UnixNativeDispatcher`). This version never uses both `stat64` and `statx`. It only uses `statx` if its available and uses the older `stat64` otherwise.
> 
> I was chatting with @bplb about this change, mostly about testing and maintainability. We both agreed that this PR isn't the right place to do the refactoring, there is a lot disruptive changes needed to allow overriding of what is currently in the Unix* code. So if it's okay with you, we think go back the original/smaller change in UnixNativeDispatcher.c but use stat or statx, before both, as you have in the second iteration. Would that be okay with you?

Fair enough. Hopefully we can make progress on that third version then.

**Comment by jerboaa** [comment]
@AlanBateman Please take another look. It's now back with using the native only. It only does a single `statx` or `stat64` call depending on support of the underlying system.

Example:
```
$ strace -f ./java LastModified test.txt 2>&1 | grep stat | grep test.txt
[pid 200843] stat("test.txt", {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
$ strace -f ./java LastModified test.txt 2>&1 | grep stat | grep test.txt
[pid 200879] statx(AT_FDCWD, "test.txt", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0644, stx_size=0, ...}) = 0
```

Long term something like the [v2 patch](https://github.com/jerboaa/jdk/compare/d75d9774c806e4bf73caa69cd78c31a132e4c812..JDK-8316304-statx-create-time-new-v2) seems more appropriate, IMO.

Thoughts?

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c [hunk 1]
```diff
@@ -143,6 +234,10 @@ typedef int futimesat_func(int, const char *, const struct timeval *);
 typedef int futimens_func(int, const struct timespec *);
 typedef int lutimes_func(const char *, const struct timeval *);
 typedef DIR* fdopendir_func(int);
+#if defined(__linux__)
+typedef int statx_func(int dirfd, const char *restrict pathname, int flags,
+                 unsigned int mask, struct statx *restrict statxbuf);
```
Comment (bplb) [inline src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:239]: Align `unsigned int mask` under `int dirfd`.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java [hunk 2]
```diff
@@ -22,14 +22,16 @@
...
+ * @bug 8011536 8151430 8316304
  * @summary Basic test for creationTime attribute on platforms/file systems
  *     that support it.
  * @library  ../.. /test/lib
+ * @modules java.base/sun.nio.fs:open
  * @build jdk.test.lib.Platform
  * @run main CreationTime
  */
 
+import java.lang.reflect.Method;
```
Comment (bplb) [inline test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:34]: Instead of using reflective access, would it be possible to use the "os.version" property and a minimum kernel version (4.11?)?

```
jshell> System.getProperty("os.version")
$1 ==> "5.19.0-50-generic"

jshell> 
bpb@bpb-vb-u2204:~$ uname -a
Linux bpb-vb-u2204 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c [hunk 3]
```diff
@@ -117,7 +208,7 @@ static jfieldID attrs_st_mtime_nsec;
 static jfieldID attrs_st_ctime_sec;
 static jfieldID attrs_st_ctime_nsec;
 
-#ifdef _DARWIN_FEATURE_64_BIT_INODE
+#if defined(_DARWIN_FEATURE_64_BIT_INODE) || defined(__linux__)
 static jfieldID attrs_st_birthtime_sec;
```
Comment (davidvoit) [inline src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:212]: birthtime_nsec missing? Just set it to zero on darwin and use the value under linux?

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java (hunk 2 above)
Comment (jerboaa) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:34]: It's not the full story. On an alpine build, on `5.19.0-50` it would report the wrong value. It's not supported, since the libc impl doesn't support it. The kernel itself would as a regular, non-alpine build, attests. I could use `!Platform.isMusl()` in addition if that sounds OK?

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c (hunk 3 above)
Comment (jerboaa) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:212]: I've deliberately omitted that change here, not sure if this change of behaviour is wanted as it would add a field in `UnixFileAttributes` (it was part of the v2 patch). @bplb @AlanBateman Thoughts? I can include it of course, but don't want to go in circles.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java (hunk 2 above)
Comment (jerboaa) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:34]: Hmm, @bplb `Platform.isMusl()` doesn't seem to work reliably. Running an alpine binary on Linux (Fedora) in my case, breaks this test as it gets `Platform.isMusl() == false`. Also, there is a chance where the JDK runs on an old glibc (<2.28) and new enough kernel, where this wouldn't work either. Using the reflective approach seems most consistent with what the code is actually doing. More thoughts?

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c (hunk 3 above)
Comment (davidvoit) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:212]: Understood, seems just a little bit silly that a limitation in a different kernel (darwin) artificially limits the birthtime here, while it easily accessible with statx. Otherwise this patch series looks quite good!

Comment (jerboaa) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:212]: Well, I've reconsidered. It's fairly trivial to support, so I've added it. The latest patch does this. It's an incremental webrev change so we can go back if not desired.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java (hunk 2 above)
Comment (jerboaa) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:34]: For now I'd like to keep the reflective approach until we know a better way to determine it.

File: src/java.base/unix/classes/sun/nio/fs/UnixFileAttributes.java [hunk 4]
```diff
@@ -25,10 +25,15 @@
 
 package sun.nio.fs;
 
-import java.nio.file.attribute.*;
-import java.util.concurrent.TimeUnit;
-import java.util.Set;
+import java.nio.file.attribute.BasicFileAttributes;
```
Comment (AlanBateman) [inline src/java.base/unix/classes/sun/nio/fs/UnixFileAttributes.java:28]: I assume you'll update the copyright date on this file.

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c [hunk 5]
```diff
@@ -528,14 +678,32 @@ Java_sun_nio_fs_UnixNativeDispatcher_stat0(JNIEnv* env, jclass this,
...
     if (err == 0) {
-        prepAttributes(env, &buf, attrs);
+        copy_stat64_attributes(env, &buf, attrs);
         return 0;
     } else {
         return errno;
     }
+#if defined(__linux__)
+    }
+#endif
```
Comment (AlanBateman) [inline src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:706]: Can you replace this with #if defined(__linux) .. #else .. #endif as it will make it easier to read. There are several places where we'll need to fix the indent with nested ifdef usage as it's hard to ready right now.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java [hunk 6]
```diff
@@ -118,6 +129,18 @@ static void test(Path top) throws IOException {
...
 
+    // Reflective implementation so as to compile on non-Linux platforms
+    private static boolean unixDispatcherSupportsBirthTime() {
+        try {
+            Class<?> unixDispatcher = Class.forName(UNIX_DISPATCHER_CLASSNAME);
+            Method supportsBirthTime = unixDispatcher.getDeclaredMethod(SUPPORTS_BIRTH_TIME_METHOD);
+            supportsBirthTime.setAccessible(true);
+            return (boolean)supportsBirthTime.invoke(null);
+        } catch (Throwable e) {
+            throw new RuntimeException("Illegal state!");
```
Comment (AlanBateman) [inline test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:140]: I agree with Brian, we need to find a better way to do this.

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c [hunk 7]
```diff
@@ -229,10 +341,14 @@ Java_sun_nio_fs_UnixNativeDispatcher_init(JNIEnv* env, jclass this)
...
     CHECK_NULL_RETURN(attrs_st_ctime_nsec, 0);
 
-#ifdef _DARWIN_FEATURE_64_BIT_INODE
+#if defined(_DARWIN_FEATURE_64_BIT_INODE) || defined(__linux__)
     attrs_st_birthtime_sec = (*env)->GetFieldID(env, clazz, "st_birthtime_sec", "J");
     CHECK_NULL_RETURN(attrs_st_birthtime_sec, 0);
 #endif
+#if defined (__linux__) // Linux has nsec granularity
+    attrs_st_birthtime_nsec = (*env)->GetFieldID(env, clazz, "st_birthtime_nsec", "J");
+    CHECK_NULL_RETURN(attrs_st_birthtime_sec, 0);
```
Comment (AlanBateman) [inline src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:350]: This should check attrs_st_birthtime_nsec.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java (hunk 6 above)
Comment (jerboaa) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:140]: Sure, happy to. Any suggestions?

File: src/java.base/unix/classes/sun/nio/fs/UnixFileAttributes.java (hunk 4 above)
Comment (jerboaa) [reply src/java.base/unix/classes/sun/nio/fs/UnixFileAttributes.java:28]: OK.

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c (hunk 5 above)
Comment (jerboaa) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:706]: > Can you replace this with #if defined(__linux) .. #else .. #endif as it will make it easier to read.

I'm not sure I follow. We need the `statx` code *and* the old `stat64` code on Linux as that's the fall-back code when `statx` isn't supported. We don't need the `statx` code on other platforms. If I used `#if defined(__linux__) #else ... #endif` instead, I wouldn't get the stat64 code on Linux without duplication. What am I missing?

Comment (jerboaa) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:706]: I've added indents. Not sure if it's any better.

Comment (AlanBateman) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:706]: >  What am I missing?

If you remove the "} else {" then it will be a lot simpler. The thing that I really dislike is the `#if defined(__linux__) } #endif` at the end of each function, it's not needed.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java (hunk 6 above)
Comment (jerboaa) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:140]: I'm experimenting with a native function in a test helper. Hopefully that'll be more amenable.

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c (hunk 5 above)
Comment (jerboaa) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c]: Should be fixed.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/libCreationTimeHelper.c [hunk 8]
```diff
@@ -0,0 +1,38 @@
...
+#if defined(__linux__)
+#include <dlfcn.h>
+#endif
+
+// static native boolean linuxIsCreationTimeSupported()
+JNIEXPORT jboolean JNICALL
+Java_CreationTimeHelper_linuxIsCreationTimeSupported(JNIEnv *env, jclass cls)
+{
+#if defined(__linux__)
+    void* statx_func = dlsym(RTLD_DEFAULT, "statx");
```
Comment (bplb) [inline test/jdk/java/nio/file/attribute/BasicFileAttributeView/libCreationTimeHelper.c:33]: For commit 04226fd470bc9a238e83606cb7f62ebd64d44421, which is the penultimate commit, I am seeing the build error:

```
open/test/jdk/java/nio/file/attribute/BasicFileAttributeView/libCreationTimeHelper.c:33: error: undefined reference to 'dlsym'```

Comment (bplb) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/libCreationTimeHelper.c:33]: The above build failure is fixed in commit 83347ec1c9fee2a859470fff8e391c5f6970d226.

Comment (jerboaa) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/libCreationTimeHelper.c:33]: Yes, sorry about that.

**Comment by jerboaa** [comment]
x86 (32 bit) GHA failure seems unrelated. My testing seems OK for this patch. Feel free to run your own.

Please let me know if there is anything else that still needs to be addressed.

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c [hunk 9]
```diff
@@ -71,6 +73,95 @@
 #define readdir64 readdir
 #endif
 
+#if defined(__linux__)
+// Account for the case where we compile on a system without statx
+// support. We still want to ensure we can call statx at runtime
+// if the runtime glibc version supports it (>= 2.28)
+#ifndef __NR_statx
```
Comment (tstuefe) [inline src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:80]: As long as we have to accommodate the case where struct statx is not defined, we may just as well do it always: just define a structure binary compatible to statx but named differently (e.g. my_statx) to prevent name clashes in case the structure happens to be defined already from libc; then use that structure as return type for your function pointer.

The advantage would be you don't need to know and depend on __NR_statx, and you don't need to include asm/unistd. And no two cases to build and test.

We do this already in other places, see e.g. the dynamic inclusion of mallinfo2() in os_linux.cpp.

Comment (jerboaa) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:80]: OK.

Comment (jerboaa) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c]: Should be done now in the latest patch.

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c [hunk 10]
```diff
@@ -545,12 +705,26 @@ Java_sun_nio_fs_UnixNativeDispatcher_lstat0(JNIEnv* env, jclass this,
...
+    if (my_statx_func != NULL) {
+        // Prefer statx over stat64 on Linux if it's available
+        RESTARTABLE(statx_wrapper(AT_FDCWD, path, flags, mask, &statx_buf, NO_FOLLOW_SYMLINK), err);
+        if (err == 0) {
+            copy_statx_attributes(env, &statx_buf, attrs);
+        } else {
+            throwUnixException(env, errno);
+        }
+    }
+#endif
```
Comment (tstuefe) [inline src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:722]: Are you missing a return here or did you really intent to call both  `statx` and `lstat64` ?

Comment (jerboaa) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:722]: Good catch! The original code had this in `if () ... else ...` blocks. Will fix. It needs to get fixed elsewhere too.

**Review by tstuefe — APPROVED** [review]
Looks good to me now, but Brian or Alan should okay this too.

**Comment by jerboaa** [comment]
> Looks good to me now, but Brian or Alan should okay this too.

Yes, sure. Thanks for the review!

/reviewers 2

**Comment by bplb** [comment]
> Looks good to me now, but Brian or Alan should okay this too.

@AlanBateman is away this week so I would expect this review to continue into next week.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java [hunk 11]
```diff
@@ -88,6 +88,12 @@ static void test(Path top) throws IOException {
                 supportsCreationTimeRead = true;
                 supportsCreationTimeWrite = true;
             }
+        } else if (Platform.isLinux()) {
+            // Creation time read depends on statx system call support
+            supportsCreationTimeRead = CreationTimeHelper.linuxIsCreationTimeSupported();
+            System.out.println("[Linux] Debug: supportsCreationTimeRead == " + supportsCreationTimeRead);
+            // Creation time updates are not supported on Linux
+            supportsCreationTimeWrite = false;
```
Comment (AlanBateman) [inline test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:96]: It might be simpler to use `Linker.nativeLinker().defaultLookup().find("statx").isPresent()` as that would avoid adding CreationTimeHelper. JEP 454 is proposed to target 22 so the test won't need @enablePreview.

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c [hunk 12]
```diff
@@ -177,6 +273,17 @@ static int fstatat64_wrapper(int dfd, const char *path,
 }
 #endif
 
+#if defined(__linux__)
+static int statx_wrapper(int dirfd, const char *restrict pathname, int flags,
+                         unsigned int mask, struct my_statx *restrict statxbuf,
+                         int follow_symlink) {
+    if (follow_symlink == NO_FOLLOW_SYMLINK) {
+      flags |= AT_SYMLINK_NOFOLLOW;
```
Comment (AlanBateman) [inline src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:281]: I think it would be better if statx_wrapper had the same signature as statx. Have you tried adding the AT_SYMLINK_NOFOLLOW flag at the use-site?

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java (hunk 11 above)
Comment (jerboaa) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:96]: OK. If I use that this patch will have to wait for https://github.com/openjdk/jdk/pull/15103 to get integrated before this can be merged (avoiding the need to add `@enablePreview`). But that should happen fairly soon so it should be fine.

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c (hunk 12 above)
Comment (jerboaa) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:281]: Sure, I can do that.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java (hunk 11 above)
Comment (jerboaa) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:96]: For now I'm still using `@enablePreview` and will drop before integration once it's ready.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java [hunk 13]
```diff
@@ -22,14 +22,16 @@
  */
 
 /* @test
- * @bug 8011536 8151430
+ * @bug 8011536 8151430 8316304
  * @summary Basic test for creationTime attribute on platforms/file systems
  *     that support it.
  * @library  ../.. /test/lib
  * @build jdk.test.lib.Platform
+ * @enablePreview
```
Comment (jerboaa) [inline test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:30]: FYI: This line won't be pushed as without it the test fails (currently).

**Comment by jerboaa** [comment]
> The additions to UnixNativeDispatcher looks okay, I'd just prefer for statx_wrapper to have the same sig as statx if possible.

All remaining issues should be addressed in the latest version (modulo `@enablePreview`).

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java (hunk 13 above)
Comment (AlanBateman) [inline test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:30]: It doesn't matter but I think the convention is to put `@enablePreview` before `@library` and `@build`.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java [hunk 14]
```diff
@@ -88,6 +90,12 @@ static void test(Path top) throws IOException {
                 supportsCreationTimeRead = true;
                 supportsCreationTimeWrite = true;
             }
+        } else if (Platform.isLinux()) {
+            // Creation time read depends on statx system call support
+            supportsCreationTimeRead = Linker.nativeLinker().defaultLookup().find("statx").isPresent();
+            System.out.println("[Linux] Debug: supportsCreationTimeRead == " + supportsCreationTimeRead);
```
Comment (AlanBateman) [inline test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:96]: I think you left a debug statement here, or if you didn't then maybe drop the work "Debug" as it looks out of place here.

**Review by AlanBateman — APPROVED** [review]
The update to UnixNativeDispatcher.c looks okay now.

**Review by bplb — APPROVED** [review]
Nice to see the test C code gone.

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java (hunk 13 above)
Comment (jerboaa) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java:30]: This shouldn't matter indeed as I intend to push only once #15103 is pushed not needing the `@enablePreview` annotation.

**Comment by jerboaa** [comment]
Thanks for the reviews!

File: test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java (hunk 14 above)
Comment (AlanBateman) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java]: If you do leave a trace message here then better to put it after the if-then-else so that it's clear on all platforms whether file create time is tested or not.

Comment (jerboaa) [reply test/jdk/java/nio/file/attribute/BasicFileAttributeView/CreationTime.java]: OK.

**Review by AlanBateman — APPROVED** [review]

**Review by bplb — APPROVED** [review]
+1

**Comment by jerboaa** [comment]
https://github.com/openjdk/jdk/pull/15103 has been integrated now. I've merged master and removed `@enablePreview` from the test. No other changes have been done. I'm going to do a final round of testing and will probably integrate next week Monday.

File: src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c [hunk 15]
```diff
@@ -71,6 +72,98 @@
...
+// if the runtime glibc version supports it (>= 2.28). We do this
+// by defining binary compatible statx structs in this file and
+// not relying on included headers.
+
+#ifndef __GLIBC__
+// Alpine doesn't know these types, define them
+typedef unsigned int       __uint32_t;
+typedef unsigned short     __uint16_t;
+typedef unsigned long int  __uint64_t;
+#endif
```
Comment (jerboaa) [inline src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:87]: Not sure what changed on the lastest merge from master, but I was getting compile failures on Apine without this. It's a no-op for glibc. @AlanBateman @bplb Still ok?

Comment (AlanBateman) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:87]: > Not sure what changed on the lastest merge from master, but I was getting compile failures on Apine without this. It's a no-op for glibc. @AlanBateman @bplb Still ok?

Yes, I don't have any other comments and I see you've dropped the enablePreview.

Comment (bplb) [reply src/java.base/unix/native/libnio/fs/UnixNativeDispatcher.c:87]: Likewise. Thanks.

**Review by bplb — APPROVED** [review]

**Review by Hamlin-Li — APPROVED** [review]
LGTM.

**Comment by jerboaa** [comment]
GHA's x86 (32bit) Linux tier1 test failure seems unrelated.
