### PR TITLE
8294623: gtests does not work with googletest release-1.12.0+

### PR DESCRIPTION
**Pull request by DingliZhang**
The scope of `GTEST_DECLARE_string_(internal_run_death_test)` has been changed in googletest 1.12.0 [1]. So we can see some new compiler errors as below:

```
$ bash configure --with-gtest=/home/dingli/jdk-tools/googletest && make run-test TEST="gtest:all"

* For target hotspot_variant-server_libjvm_gtest_objs_gtestMain.o:
In file included from /home/dingli/jdk-tools/googletest/googlemock/include/gmock/internal/gmock-port.h:57,
                 from /home/dingli/jdk-tools/googletest/googlemock/include/gmock/internal/gmock-internal-utils.h:49,
                 from /home/dingli/jdk-tools/googletest/googlemock/include/gmock/gmock-actions.h:145,
                 from /home/dingli/jdk-tools/googletest/googlemock/include/gmock/gmock.h:56,
                 from /home/dingli/jdk/test/hotspot/gtest/unittest.hpp:51,
                 from /home/dingli/jdk/test/hotspot/gtest/gtestMain.cpp:39:
/home/dingli/jdk/test/hotspot/gtest/gtestMain.cpp: In function 'void runUnitTestsInner(int, char**)':
/home/dingli/jdk-tools/googletest/googletest/include/gtest/internal/gtest-port.h:2181:26: error: 'FLAGS_gtest_internal_run_death_test' is not a member of 'testing::internal'; did you mean 'testing::FLAGS_gtest_internal_run_death_test'?
 2181 | #define GTEST_FLAG(name) FLAGS_gtest_##name
      |                          ^~~~~~~~~~~~
/home/dingli/jdk/test/hotspot/gtest/gtestMain.cpp:235:28: note: in expansion of macro 'GTEST_FLAG'
  235 |   if (::testing::internal::GTEST_FLAG(internal_run_death_test).length() > 0) {
      |                            ^~~~~~~~~~
/home/dingli/jdk-tools/googletest/googletest/include/gtest/internal/gtest-port.h:2181:26: note: 'testing::FLAGS_gtest_internal_run_death_test' declared here
 2181 | #define GTEST_FLAG(name) FLAGS_gtest_##name
   ... (rest of output omitted)
```

I use `GTEST_FLAG_GET` macro to detect googletest version because it was introduced at the same time as the scope of `GTEST_DECLARE_string_(internal_run_death_test)` changed.

## Testing:

- gtest:all on x86_64

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294623](https://bugs.openjdk.org/browse/JDK-8294623): gtests does not work with googletest release-1.12.0+

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk pull/10503/head:pull/10503` \
`$ git checkout pull/10503`

Update a local copy of the PR: \
`$ git checkout pull/10503` \
`$ git pull https://git.openjdk.org/jdk pull/10503/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10503`

View PR using the GUI difftool: \
`$ git pr show -t 10503`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10503.diff">https://git.openjdk.org/jdk/pull/10503.diff</a>

</details>

### CODE REVIEW

**Comment by DingliZhang** [comment]
@dholmes-ora @tstuefe Hi, could anyone please help to take a look at this PR? Thanks in advance for your time!

**Comment by dholmes-ora** [comment]
@DingliZhang I've asked if anyone is familiar enough with googletest to review this, as I am not familiar with it.

**Comment by DingliZhang** [comment]
> @DingliZhang I've asked if anyone is familiar enough with googletest to review this, as I am not familiar with it.

Hi @dholmes-ora, thank you for your help!

**Comment by dholmes-ora** [comment]
@DingliZhang According to the building.md documentation:
```
The supported version of Google Test is 1.8.1, whose source code can be obtained:

 * by downloading and unpacking the source bundle from [here](https://github.com/google/googletest/releases/tag/release-1.8.1)
 * or by checking out `release-1.8.1` tag of `googletest` project: `git clone -b release-1.8.1 https://github.com/google/googletest`
```
I don't know how old version 1.8.1 is or whether we need to expand on the supported releases here. Maybe the build folk will have an opinion? @magicus or @erikj79 .

**Comment by kimbarrett** [comment]
> I don't know how old version 1.8.1 is or whether we need to expand on the supported releases here. Maybe the build folk will have an opinion? @magicus or @erikj79 .

I don't think we need to support multiple versions of googletest.  I don't see any benefit, and doing so incurs costs.  It might be that we should update to using a newer version, but that's a very different discussion.

**Comment by rose00** [comment]
In `doc/building.md` it clearly states:

> The supported version of Google Test is 1.8.1, whose source code can be obtained…

The bug report does not say why 1.8.1 was not attempted or was not possible to use.  So this bug report is incomplete until we have sufficient reason to consider an upgrade (which is likely ot be a global upgrade) to a newer gtest.

Until sufficient evidence shows a reason to change, let's stick to our strategy of supporting a particular version of gtest, 1.8.1 at present.

Question to @DingliZhang: Is there a change to the documentation that would help people find and implement the directive to use 1.8.1?  And (of course) is there some reason 1.8.1 was impossible for you to use?

Or is all of this just a move to improve convenience for developers?  If it's a convenience move, it's too expensive, since supporting two versions of gtest is harder than supporting one.  That's why I'm looking for a possible documentation fix, to guide developers a little better.  Perhaps the `Gtest` section in `doc/testing.md` should cross-link to the section quoted above in `doc/building.md`

**Comment by DingliZhang** [comment]
@kimbarrett @magicus @rose00 Thanks for review!

I apologize for the incomplete error report due to an oversight on my part. At first I misread `Gtest` section in `doc/building.md `, only read `Gtest` section in `doc/testing.md` and used version 1.10.0 of `Gtest`. When I found out that there was a newer version of googletest I made an attempt and found the problem.

I later found out that the `doc/building.md` pointed out the supported versions of gtest and thought it would be a convenient move for developers to support latest versions of gtest.

I think it is a good idea:
> Perhaps the Gtest section in doc/testing.md should cross-link to the section quoted above in doc/building.md

Thank you all for helping me in your busy schedule! I will close this PR.

**Comment by iklam** [comment]
It would be good if we can detect the version of the googletest and report an error if it's not 1.8.1. However, in https://github.com/google/googletest/archive/refs/tags/release-1.8.1.tar.gz, I couldn't find any file that contains the version information. The only file that contains some sort of version number doesn't have the right version:

```
./googlemock/configure.ac:        [1.8.0]
```

Maybe `make doctor` can print out some hints about 1.8.1 if it finds that the gtest build has failed?

**Comment by magicus** [comment]
@iklam I agree that ideally `configure` should complain if you have the wrong version of gtest. But as you say, this is not easy to determine. :-( That was why I skipped this when we added gtest as a prerequisite. But maybe I could do like an SHA256 of the source files and check if it matches..? Hm...
