### PR TITLE
8295795: hsdis does not build with binutils 2.39+

### PR DESCRIPTION
**Pull request by robehn**
Hi please consider.

This works with 2.30, 2.34, 2.38, 2.39, 2.40, 2.41 and current master head. (tested x64 and some RV)

There are 4 changes in binutils we work around.
- zstd compressed debug sections
- libsframe added
- init_disassemble_info() change
- libbfd.a is only present in .lib directory in newer binutils builds (older it is in both directories) (I think the issue is that we never do make install, thus have dependency on internal artifact placement)

Specific to RV, there is a bug in binutils causing the standard extensions not being added to disassembler if we pass in NULL.

This no way near perfect, but at least we can build hsdis with any contemporary binutils.

Todo better I think we need to build and install binutils to check the version and then use that version to figure out what options to use when re-building and re-installing binutils for hsdis.

I asked tool-chain people about our issues, they said, you can't do that. I.e. have source dependencies on many binutils versions.

As RV is new and have new instructions added to it frequently we really need to be able to build with bleeding-edge binutils. (capstone RV is not actively worked on, llvm have many more dependencies)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295795](https://bugs.openjdk.org/browse/JDK-8295795): hsdis does not build with binutils 2.39+ (**Bug** - P4)

### Reviewers
 * [Magnus Ihse Bursie](https://openjdk.org/census#ihse) (@magicus - **Reviewer**)
 * [Daniel Jeliński](https://openjdk.org/census#djelinski) (@djelinski - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/15138/head:pull/15138` \
`$ git checkout pull/15138`

Update a local copy of the PR: \
`$ git checkout pull/15138` \
`$ git pull https://git.openjdk.org/jdk.git pull/15138/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 15138`

View PR using the GUI difftool: \
`$ git pr show -t 15138`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/15138.diff">https://git.openjdk.org/jdk/pull/15138.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/15138#issuecomment-1663935618)

### CODE REVIEW

**Comment by robehn** [comment]
I notice if you prebuild (make install) layout, this does not work.
I need to fix more.

File: make/autoconf/lib-hsdis.m4 [hunk 1]
```diff
@@ -238,9 +239,10 @@ AC_DEFUN([LIB_SETUP_HSDIS_BINUTILS],
     AC_CHECK_LIB(opcodes, disassembler, [ HSDIS_LIBS="$HSDIS_LIBS -lopcodes" ], [ binutils_system_error="libopcodes not found" ])
     AC_CHECK_LIB(iberty, xmalloc, [ HSDIS_LIBS="$HSDIS_LIBS -liberty" ], [ binutils_system_error="libiberty not found" ])
     AC_CHECK_LIB(z, deflate, [ HSDIS_LIBS="$HSDIS_LIBS -lz" ], [ binutils_system_error="libz not found" ])
+    AC_CHECK_LIB(sframe, frame, [ HSDIS_LIBS="$HSDIS_LIBS -lsframe" ], )
     HSDIS_CFLAGS="-DLIBARCH_$OPENJDK_TARGET_CPU_LEGACY_LIB"
   elif test "x$BINUTILS_DIR" != x; then
-    if test -e $BINUTILS_DIR/bfd/libbfd.a && \
+    if test -e $BINUTILS_DIR/bfd/.libs/libbfd.a && \
```
Comment (magicus) [inline make/autoconf/lib-hsdis.m4:245]: The use of `.libs` here looks a bit scary. I have not looked in detail at the binutils build system, but it sounds like a temporary/internal file. What is the rationale?

File: make/autoconf/lib-hsdis.m4 [hunk 2]
```diff
@@ -251,7 +253,11 @@ AC_DEFUN([LIB_SETUP_HSDIS_BINUTILS],
         HSDIS_CFLAGS="$HSDIS_CFLAGS -I$BINUTILS_DIR/include -I$BINUTILS_DIR/bfd"
       fi
       HSDIS_LDFLAGS=""
-      HSDIS_LIBS="$BINUTILS_DIR/bfd/libbfd.a $BINUTILS_DIR/opcodes/libopcodes.a $BINUTILS_DIR/libiberty/libiberty.a $BINUTILS_DIR/zlib/libz.a"
+      HSDIS_LIBS="$BINUTILS_DIR/bfd/.libs/libbfd.a $BINUTILS_DIR/opcodes/libopcodes.a $BINUTILS_DIR/libiberty/libiberty.a $BINUTILS_DIR/zlib/libz.a"
+      # If we have libsframe add it.
+      if test -e $BINUTILS_DIR/libsframe/.libs/libsframe.a; then
+        HSDIS_LIBS="$BINUTILS_DIR/bfd/.libs/libbfd.a $BINUTILS_DIR/opcodes/libopcodes.a $BINUTILS_DIR/libiberty/libiberty.a $BINUTILS_DIR/zlib/libz.a $BINUTILS_DIR/libsframe/.libs/libsframe.a"
```
Comment (magicus) [inline make/autoconf/lib-hsdis.m4:259]:
```suggestion
        HSDIS_LIBS="$HSDIS_LIBS $BINUTILS_DIR/libsframe/.libs/libsframe.a"
```

...with the same caveat as above -- why use '.libs'?

**Comment by magicus** [comment]
Thanks for your effort of getting hsdis to work with a wider range of binutils! This has been problematic for a while.

File: make/autoconf/lib-hsdis.m4 (hunk 1 above)
Comment (robehn) [reply make/autoconf/lib-hsdis.m4:245]: We never do 'make install' , so we are using the internal place of files.
Make install do not install some of the dependency we have (some h-files we use are not part of binutils installation, e.g. bfdver.h).

So we are stuck between hard place and a rock, we can't use the installed binutils file-tree, so we must keep using the internal build layout.

File: make/autoconf/lib-hsdis.m4 (hunk 2 above)
Comment (robehn) [reply make/autoconf/lib-hsdis.m4:259]: Same answer, that is the layout of the build-tree and that is what we are using,

**Comment by robehn** [comment]
> Thanks for your effort of getting hsdis to work with a wider range of binutils! This has been problematic for a while.

Thanks for having a look!

File: make/autoconf/lib-hsdis.m4 (hunk 1 above)
Comment (robehn) [reply make/autoconf/lib-hsdis.m4:245]: It may be possible to read some elf header about binutils version.
I.e. do make install from our build system, then reading out version from elf section and pass that into our build.

Comment (magicus) [reply make/autoconf/lib-hsdis.m4:245]: I'm still not really happy about this. The old solution without .libs has worked before -- has anything changed in newer versions of binutils? 

Also, we support building binutils in place as a convenience, but it should also be possible to just set a hsdis path, and in that case we cannot presume that the .libs layout is kept.

I suggest you change this to both eat the cake and have it -- first check for the lib in the original location (without .libs), and if it is not found there, check in .libs. This is perhaps not necessary here in LIB_BUILD_BINUTILS, but it definitely is in LIB_SETUP_HSDIS_BINUTILS. It will make the code a few lines longer but more robust.

Comment (magicus) [reply make/autoconf/lib-hsdis.m4:245]: > It may be possible to read some elf header about binutils version. I.e. do make install from our build system, then reading out version from elf section and pass that into our build. As we need to know the signature of init_disassemble_info() which is different between binutils versions.

Trying to understand what you are really saying here. If we accept this patch, it will no longer be possible to use a normally installed binutils, since the BFD_VERSION constant (via bfdver.h) is not available? 

That is not good; the idea of building binutils locally was supposed to be a convenience, not a requirement.

Comment (robehn) [reply make/autoconf/lib-hsdis.m4:245]: Both options --with-binutils= and --with-binutils-src= grab atrifact from temporary internal build layout.
If you do "make install" and point --with-binutils= to that directory the layout is diffrent and you get:
--with-binutils=/home/rehn/binutils-2.39 gives:
configure: error: /home/rehn/binutils-2.39 does not contain a proper binutils installation

We can't use my distro native or a installed binutils.

> I'm still not really happy about this. The old solution without .libs has worked before -- has anything changed in newer versions of binutils?

As the PR says: "libbfd.a is only present in .lib directory in newer binutils builds (older it is in both directories)"
We are depending on their build system artifact layout, this is not a stable interface.
You need todo make install to get the stable layout, then it would be "./lib/libsframe.a".

> 
> Also, we support building binutils in place as a convenience, but it should also be possible to just set a hsdis path, and in that case we cannot presume that the .libs layout is kept.

binutils do not support having source dependency on multiple versions (i asked about this).
That is way the binutils tools are co-hosted (gdb, gas, ...)
Which I assume is on of the reasons it is not possible form headers to check version.
But as I said we today do not support using the installation since we have wrong path for libs.

> 
> I suggest you change this to both eat the cake and have it -- first check for the lib in the original location (without .libs), and if it is not found there, check in .libs. This is perhaps not necessary here in LIB_BUILD_BINUTILS, but it definitely is in LIB_SETUP_HSDIS_BINUTILS. It will make the code a few lines longer but more robust.

As I said it have been under .lib in all version of binutils I checked. This is not a new location.
So it seem like it's much better to check the directory it is always in (so far), no?

> > It may be possible to read some elf header about binutils version. I.e. do make install from our build system, then reading out version from elf section and pass that into our build. As we need to know the signature of init_disassemble_info() which is different between binutils versions.
> 
> Trying to understand what you are really saying here. If we accept this patch, it will no longer be possible to use a normally installed binutils, since the BFD_VERSION constant (via bfdver.h) is not available?
> 
> That is not good; the idea of building binutils locally was supposed to be a convenience, not a requirement.

"--with-binutils" don't use the "normally installed binutils" it assume that the directory is the build directory, which as have a different layout than "make install". So that case do not work today.

Summarize, the layout we are using for both hsdis= and hsdis-src= are the internal temporary layout before you do make install. Therefore we have access to bfdver.h and can determine API version.

This do not handle the case if you built with dependency on zstd.

**Comment by theRealAph** [comment]
I dunno Robbin, is this really the sort of stuff we should be doing? Binutils is looking less useful as a base for hsdis.
I see your problem, but I can't help wondering if rather than trying to keep up with Binutils it'd be a better use of time to work on keeping Capstone up to date.

**Comment by robehn** [comment]
> I dunno Robbin, is this really the sort of stuff we should be doing? Binutils is looking less useful as a base for hsdis. I see your problem, but I can't help wondering if rather than trying to keep up with Binutils it'd be a better use of time to work on keeping Capstone up to date.

I agree, we shouldn't be doing this.
The hsdis-binutils should probably be in binutils, similar to perf jvmti agent in kernel tools/perf/jvmti.

Capstone is not worked on by any rv folks, it had a init push of 'base' isa 4y ago and left at that.
Just this year it will around 5-10 new extension to the ISA, with major ones as vector.
Which means it would be us hotspot dev. that needs to everything in capstone.
If so it would be easier to add the disassembler to hotspot, which means we can unittest that you added the disassembler part for your new instruction in the assembler.

File: make/autoconf/lib-hsdis.m4 (hunk 1 above)
Comment (robehn) [reply make/autoconf/lib-hsdis.m4:245]: I forgot about --with-binutils=system:
This one is broken:
/home/rehn/source/jdk/open/src/utils/hsdis/binutils/hsdis-binutils.c:60:10: fatal error: libiberty.h: No such file or directory
   60 | #include <libiberty.h>

This include is under "libiberty/libiberty.h".

And yes, if we fix that bfdver.h would be an issue, you are correct.

Maybe we check just test what API version in make system by testing the init_disassemble_info_from_bfd signature.
Thus removing bfdver.h.

For a system build we would have deps on libzstd.so, if it was not compiled without it.

**Comment by theRealAph** [comment]
> Capstone is not worked on by any rv folks, it had a init push of 'base' isa 4y ago and left at that. Just this year it will around 5-10 new extension to the ISA, with major ones as vector. Which means it would be us hotspot de. that needs to everything in capstone. If so it would be easier to add the disassembler to hotspot; we can unittest that you added the disassembler part for your new instruction in the assembler.

Maybe, but would it really be easier? I don't see that it would be _significantly_ easier, and it would be much more riscv community friendly to work on the shared disassembler.

**Comment by robehn** [comment]
> Maybe, but would it really be easier? I don't see that it would be _significantly_ easier, and it would be much more riscv community friendly to work on the shared disassembler.

The build would be easier, no deps at all and could be shipped as part of the release since we control license. (license not an issue with capstone) And testing as mentioned.
The question if a third shared disassembler worth it, considering the relative small community.
I raised the Q, let's wait a bit and see...

Just want to mention that RV _can_ have same OP code for multiple instructions (vendor specific), binutils and llvm have the infrastructure to handle this, a quick peek at capstone made me think this might be an issue.
Thus task may not be as trivial 'add missing' instructions.
https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=include/opcode/riscv-opc.h;h=2a26c45f0c24c66937cb405f3a6d3b5c0b70acbb;hb=HEAD#l2323

**Comment by theRealAph** [comment]
> > Maybe, but would it really be easier? I don't see that it would be _significantly_ easier, and it would be much more riscv community friendly to work on the shared disassembler.
> 
> The build would be easier, no deps at all and could be shipped as part of the release since we control license. (license not an issue with capstone) 

Building hsdis in a shippable form is key for me. As I see it, binutils is out of the question because its licence is incompatible, (IANAL) LLVM is too large, and only Capstone fits. 

> And testing as mentioned.

Well, yeah, but then if we had our own disassembler we'd have the cost too.

 > Just want to mention that RV _can_ have same OP code for multiple instructions (vendor specific),

Ouch ouch ouch no! That is the way of disaster. 

> binutils and llvm have the infrastructure to handle this, a quick peek at capstone made me think this might be an issue. Thus task may not be as trivial 'add missing' instructions. 

Yeah. These mostly look like kernel magic, though.

**Comment by magicus** [comment]
This discussion branched away a bit. Let me try to summarize:

About hsdis backends:
* Capstone is easier for us to interact with, and has no license issues blocking a distributable hsdis. In that way it is definitely preferable, just as @theRealAph says. Ideally, it should be our first hand choice of hsdis backend.
* However, it is also the case that the backend must be useful for the developers. Robin's point is that for RISC-V, only binutils is really usable as of now, not Capstone. Hence we must keep our binutils support alive.

About this patch:
* Our support for `--with-binutils=system` is currently broken. 
* Currently, the `--with-binutils=` argument works well if pointed to a binutils build location, but not if pointed to an installed location. 
* The above issues is relatively easy to fix as the code looks right now, but if this PR is accepted, it will be much harder (or impossible) to fix, thus cementing that only a binutils build location will be acceptable.
* If there were some other way to determine the version of BFD used for building binutils, then we could have this patch, as well as being able to support system binutils and/or a installed location.

Correct me if I'm wrong.

The upshot of all this is that I am in favor of keeping binutils support alive, but I am a bit hesitant about locking in on the need for a installation directory. Instead, I'd rather see that we try to fix the current bugs with `system` and an installation directory. 

It would be really great if we could find a way to deduce the bfd version. If this is not possible, a less ideal solution could be to e.g. assume a certain bfd version if using a system or installed location binutils, and/or possibly allow the user to set this value from configure options. (And if we do have a binutils build location, we can of course do as in this patch and get it from bfdver.h -- but maybe extract the value in configure instead).

**Comment by robehn** [comment]
Yes!

Added API check in conf instead, thus removing bfdver.h.
Test both binutils tip and 2.38, with both --with-binutils=/--with-binutils-src=.

File: make/autoconf/lib-hsdis.m4 [hunk 3]
```diff
@@ -251,10 +253,31 @@ AC_DEFUN([LIB_SETUP_HSDIS_BINUTILS],
...
```
Comment (magicus) [inline make/autoconf/lib-hsdis.m4:259]: Just append the additional lib.

```suggestion
        HSDIS_LIBS="$HSDIS_LIBS $BINUTILS_DIR/libsframe/.libs/libsframe.a"
```

File: make/autoconf/lib-hsdis.m4 [hunk 4]
```diff
@@ -251,10 +253,31 @@ AC_DEFUN([LIB_SETUP_HSDIS_BINUTILS],
...
+      fi
     fi
   fi
 
+  AC_MSG_CHECKING([Checking binutils API])
+  if test -n "$BINUTILS_SRC"; then
+    include_dis="#include \"$BINUTILS_SRC/include/dis-asm.h\""
```
Comment (magicus) [inline make/autoconf/lib-hsdis.m4:266]: All this quoting and duplication seems quite messy. Can't you just set e.g. `binutils_include_dir` to either `%BINUTILS_SRC/include` or `%BINUTILS_DIR/include`, and then just do 

```
AC_LANG_PROGRAM([#include "$binutils_include_dir/dis-asm.h"], ...
```
?

(Code written in github editor; warning for quoting mistakes etc)

**Comment by magicus** [comment]
This is starting to look much better!

I still don't understand why you want to change `$BINUTILS_DIR/bfd/libbfd.a` to `$BINUTILS_DIR/bfd/.libs/libbfd.a`. The old path has worked fine before. Is this something that has stopped working in newer versions of binutils?

**Comment by magicus** [comment]
Nevertheless, I believe the .libs issue needs to be addressed as well, otherwise this will be a regression for older versions of binutils that are in a non-build installed location.

That is, you need to break out the check for `libbfd.a`, and look for it first in `bfd` and secondly in `bfd/.libs`.

**Comment by robehn** [comment]
> Nevertheless, I believe the .libs issue needs to be addressed as well, otherwise this will be a regression for older versions of binutils that are in a non-build installed location.
> 
> That is, you need to break out the check for `libbfd.a`, and look for it first in `bfd` and secondly in `bfd/.libs`.

All version I checked (2.30, 2.34, 2.38, 2.39, 2.40, 2.41) all libs are in .libs.
And make install copy them from the .lib folder.
`libtool: install: /usr/bin/install -c .libs/libopcodes.a /home/rehn/source/gdb/binutils-gdb/install/lib/libopcodes.a`

Arguably we should only use .libs directory,

File: make/autoconf/lib-hsdis.m4 (hunk 4 above)
Comment (robehn) [reply make/autoconf/lib-hsdis.m4:266]: I can check. No really my usual place in the world doing autoconf :)

File: make/autoconf/lib-hsdis.m4 (hunk 3 above)
Comment (robehn) [reply make/autoconf/lib-hsdis.m4]: Fixed

**Comment by robehn** [comment]
Ping @magicus!

We have two cases system or built/pre-built.
1: For system we use -lbfd.
2: For built or pre-built we use the same artifact as make install is using in new and old versions.

There is no regression ?

**Comment by magicus** [comment]
Sorry, I have not been able to look at this. I'll get back to this shortly.

**Comment by robehn** [comment]
> I still think we're talking past each other here.
> 
> I am talking about situation 3: We have built and installed it locally with `make install`, and have removed the installation directory (or at least points the configure argument to the installed directory).
> 
> In this case, you will not have a .libs directory.
> 
> I still don't see why it would be such big deal to check for the required files in both the directory directly, and then, if it is not found, check in a `.libs` directory? That's all I request, to increase the likelyhood that this works with many different kinds of setup.

Yes, as I have already said both in PR and in the comments, we do no support option 3, not now and not with this patch.
And the path you are suggesting (the one we have now) is wrong for "situation 3".

As you can see from the output above the library is moved from:
{source-dir}/bfd/.libs/libbfd.a to {install-dir}/lib/libbfd.a

You keep insisting that we should look in:
> That is, you need to break out the check for `libbfd.a`, and look for it first in `bfd` and secondly in `bfd/.libs`.
But an installation doesn't even have a "bfd" directory.

In all recent binutils 2.30->trunk it is always present in .libs/libbfd.a (again situation 3 is not support now and not with this patch)

Yes we should add for option 3, but that is not in scope here.

**Comment by magicus** [comment]
Ok, fine, let's go with this patch then.

**Review by magicus — APPROVED** [review]

**Comment by robehn** [comment]
> Ok, fine, let's go with this patch then.

Thank you, but I was unhappy with the situation.

I redid the patch:
- Source build now do make install, then uses same steps as pre-built after the "make install".
- Prebuilt now uses the installed directory. --with-binutils-src={installation_directory}
- Checking for API break now works on system also.

* Since libz is not installable from a binutils build, we have to use the system libz.

Source works with 2.30/2.38/trunk (and incremental source configure do not need to re-build)
Prebuilt works with 2.30/2.38/trunk
System works

AFAICT everything now is working.
But with two caveats:
- zlib mentioned above.
- you must configure with "--enable-install-libiberty" and install that if you are building your self.

@magicus ? :)

**Comment by robehn** [comment]
@djelinski can you test it out?

**Review by magicus — APPROVED** [review]
This looks soo much better! Thank you for taking the time to clean it up and expand/generalize the functionality. Now I think the binutils functionality is close to as good as we're ever going to get it.

**Comment by robehn** [comment]
> This looks soo much better! Thank you for taking the time to clean it up and expand/generalize the functionality. Now I think the binutils functionality is close to as good as we're ever going to get it.

Thanks you, great that you like this also!

**Comment by djelinski** [comment]
Would you know if this code is still alive? https://github.com/openjdk/jdk/blob/d9ce525a1c27f41ef66c39b3ec18e3a87bbd8dd3/make/devkit/Tools.gmk#L405-L406

(I was searching for the remaining references to libiberty, and this came up)

**Review by djelinski — APPROVED** [review]
Checked that this works on Ubuntu with 2.30, 2.41 and system binutils. LGTM.

**Comment by robehn** [comment]
Thanks you! I don't know the answer to your question, devkit stuff.

**Comment by magicus** [comment]
The devkit code is for building our own gcc binary, something we do for the Oracle-internal CI pipeline. It has no relevance to the rest of the product, and certainly not this PR.

File: make/autoconf/lib-hsdis.m4 [hunk 5]
```diff
@@ -223,41 +230,57 @@ AC_DEFUN([LIB_SETUP_HSDIS_BINUTILS],
...
-      HSDIS_LDFLAGS=""
-      HSDIS_LIBS="$BINUTILS_DIR/bfd/libbfd.a $BINUTILS_DIR/opcodes/libopcodes.a $BINUTILS_DIR/libiberty/libiberty.a $BINUTILS_DIR/zlib/libz.a"
+      AC_CHECK_LIB(z, deflate, [ HSDIS_LIBS="$HSDIS_LIBS -lz" ], AC_MSG_ERROR([libz not found]))
+    else
+      AC_MSG_ERROR(["$BINUTILS_INSTALL_DIR/libs/ must contain libbfd.a, libopcodes.a, libiberty.a"])
     fi
   fi
 
+  AC_MSG_CHECKING([Checking binutils API])
+  AC_COMPILE_IFELSE([AC_LANG_PROGRAM([#include $disasm_header],[[void foo() {init_disassemble_info(0, 0, 0, 0);}]])],
```
Comment (galderz) [inline make/autoconf/lib-hsdis.m4:272]: Seems to me this is not working as expected but I don't have an env to verify this.

I've been working on something similar to deal with `capstone` API changes and the pattern here seemed to not compile but not for the reasons expected.

For example, I created:

```
AC_COMPILE_IFELSE([AC_LANG_PROGRAM([#include $capstone_header],[[void foo() {cs_arch test = CS_ARCH_AARCH64;}]])],
```

And when I looked the compilation error it showed:

```
conftest.c:27:12: error: function definition is not allowed here
void foo() {cs_arch test = CS_ARCH_AARCH64;}
           ^
1 error generated.
configure:142919: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "OpenJDK"
| #define PACKAGE_TARNAME "openjdk"
| #define PACKAGE_VERSION "openjdk"
| #define PACKAGE_STRING "OpenJDK openjdk"
| #define PACKAGE_BUGREPORT "build-dev@openjdk.org"
| #define PACKAGE_URL "https://openjdk.org"
| #define HAVE_STDIO_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define STDC_HEADERS 1
| #define HAVE_STDIO_H 1
| #define SIZEOF_INT_P 8
| #define HAVE_CUPS_CUPS_H 1
| #define HAVE_CUPS_PPD_H 1
| /* end confdefs.h.  */
| #include "/Users/galder/opt/capstone/include/capstone/capstone.h"
| int
| main (void)
| {
| void foo() {cs_arch test = CS_ARCH_AARCH64;}
|   ;
|   return 0;
| }
```

So, the code was not compiling not because of the wrong `cs_arch` value but because you cannot define a method within main.

Instead I made my `AC_COMPILE_IFELSE` looks like this:

```
AC_COMPILE_IFELSE([AC_LANG_PROGRAM([#include $capstone_header],[[cs_arch test = CS_ARCH_AARCH64;]])],
```

And that works as expected. For example, when using a `capstone` library that supports `CS_ARCH_AARCH64`, it does:

```
configure:142754: result: 'capstone'
configure:142767: checking for capstone
configure:142770: result: /Users/galder/opt/capstone
configure:142906: checking capstone aarch64 arch name
configure:142919: /usr/bin/clang -c  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks conftest.c >&5
configure:142919: $? = 0
configure:142922: result: AARCH64
```

And when the capstone library does not have `CS_ARCH_AARCH64`, the compilation error I get is the expected one:

```
conftest.c:27:16: error: use of undeclared identifier 'CS_ARCH_AARCH64'; did you mean 'CS_ARCH_ARM64'?
cs_arch test = CS_ARCH_AARCH64;
               ^~~~~~~~~~~~~~~
               CS_ARCH_ARM64
/Users/galder/opt/capstone-5/include/capstone/capstone.h:76:2: note: 'CS_ARCH_ARM64' declared here
        CS_ARCH_ARM64,          ///< ARM-64, also called AArch64
        ^
1 error generated.
configure:142919: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "OpenJDK"
| #define PACKAGE_TARNAME "openjdk"
| #define PACKAGE_VERSION "openjdk"
| #define PACKAGE_STRING "OpenJDK openjdk"
| #define PACKAGE_BUGREPORT "build-dev@openjdk.org"
| #define PACKAGE_URL "https://openjdk.org"
| #define HAVE_STDIO_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_UNISTD_H 1
| #define STDC_HEADERS 1
| #define HAVE_STDIO_H 1
| #define SIZEOF_INT_P 8
| #define HAVE_CUPS_CUPS_H 1
| #define HAVE_CUPS_PPD_H 1
| /* end confdefs.h.  */
| #include "/Users/galder/opt/capstone-5/include/capstone/capstone.h"
| int
| main (void)
| {
| cs_arch test = CS_ARCH_AARCH64;
|   ;
|   return 0;
| }
```

/cc @theRealAph

Comment (galderz) [reply make/autoconf/lib-hsdis.m4:272]: To make it clear, seems to me this line should be this instead:

```
AC_COMPILE_IFELSE([AC_LANG_PROGRAM([#include $disasm_header],[[init_disassemble_info(0, 0, 0, 0);]])],
```

You could probably remove the `;` too seems that seems to also be included.

Comment (robehn) [reply make/autoconf/lib-hsdis.m4:272]: Yes, you are correct, this was not my intention.
For some reason I mixed up AC_LANG_SOURCE and AC_LANG_PROGRAM.

But nested function are fine, so there is actually no issue with it.

Comment (galderz) [reply make/autoconf/lib-hsdis.m4:272]: > But nested function are fine, so there is actually no issue with it.

Is it? The compilation error above says "error: function definition is not allowed here". It seems to me is saying that the compilation fails because of the nested function. Am I missing something?

Comment (robehn) [reply make/autoconf/lib-hsdis.m4:272]: Yea, you are correct. Apparently the gcc extension is not turned off even if you use -ansi.
clang on the other hand complains.

@galderz your suggest patch is correct, can you open PR ?

Comment (magicus) [reply make/autoconf/lib-hsdis.m4:272]: @robehn Way ahead of you: https://bugs.openjdk.org/browse/JDK-8320663 :)

Comment (robehn) [reply make/autoconf/lib-hsdis.m4:272]: Thank you @magicus !

Comment (galderz) [reply make/autoconf/lib-hsdis.m4:272]: That was fast! Thx @magicus and thanks @robehn for verifying things!
