### PR TITLE
8366837: Clean up gensrc by spp.Spp

### PR DESCRIPTION
**Pull request by magicus**
Several java classes in java.base is generated from templates using SPP, the "Stream Preprocessor". Unfortunately much of this code is very old and has survived unchanged since pre-JDK 7. It does not follow modern makefile standards for abstraction, safe coding practices, etc. In short, they have been a thorn in the side for a long time, and the time has finally come to clean them up.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8366837](https://bugs.openjdk.org/browse/JDK-8366837): Clean up gensrc by spp.Spp (**Bug** - P3)

### Reviewers
 * [Erik Joelsson](https://openjdk.org/census#erikj) (@erikj79 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/27078/head:pull/27078` \
`$ git checkout pull/27078`

Update a local copy of the PR: \
`$ git checkout pull/27078` \
`$ git pull https://git.openjdk.org/jdk.git pull/27078/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 27078`

View PR using the GUI difftool: \
`$ git pr show -t 27078`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/27078.diff">https://git.openjdk.org/jdk/pull/27078.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/27078#issuecomment-3258833112)
</details>

### CODE REVIEW

**Comment by magicus** [comment]
I have verified that the generated java source code in gensrc is byte-by-byte identical with and without this patch. That is really all that is needed in terms of correctness, but to make sure I do not run into some unexpected problem I am also running a confirmation round on our internal CI.

**Comment by magicus** [comment]
Hm, something is messing up the command lines on the GHA hosts. Funny, I did not see it when testing elsewhere. I'll look into it.

**Comment by magicus** [comment]
For the record: the changes in the X-Coder template means that additional empty lines will be inserted in the generated source. This has no real effect on anything substantial, but it means that line numbers change, which make a complete byte-by-byte comparison fail for anything that is dependent on these classes.

**Comment by magicus** [comment]
This has passed Oracle internal CI testing for "builds-infra" tier 1-5.

File: make/modules/java.base/gensrc/GensrcBuffer.gmk [hunk 1]
```diff
@@ -28,363 +28,222 @@ ifeq ($(INCLUDE), true)
...
+    )
+
+    # Inject these snippets in the file generated by GEN_BUFFER_$1
+    $$($1_REAL_OUTPUT): $$($1_OUTPUT) $$($1_BIN_SNIPPET_FILES)
+	$$(call LogInfo, Concatenating buffer class bin snippets for $1)
+        # Delete everything from the line containing #BIN and below
+	$$(SED) -e '/#BIN/,$$$$d' < $$($1_OUTPUT) > $$($1_REAL_OUTPUT).tmp
+	$$(CAT) $$($1_BIN_SNIPPET_FILES) >> $$($1_REAL_OUTPUT).tmp
+	$$(ECHO) "}" >> $$($1_REAL_OUTPUT).tmp
+	$$(MV) $$($1_REAL_OUTPUT).tmp $$($1_REAL_OUTPUT)
```
Comment (erikj79) [inline make/modules/java.base/gensrc/GensrcBuffer.gmk:162]: Indentation looks off here.

Comment (magicus) [reply make/modules/java.base/gensrc/GensrcBuffer.gmk:162]: I think it is per our standard. It seems the Github diff viewer expands tabs to 4 spaces, which makes it looks incorrect.

Comment (magicus) [reply make/modules/java.base/gensrc/GensrcBuffer.gmk:162]: Turns out you can actually change the tab size setting on GitHub. They set 4 as default but you can change it to 8 at https://github.com/settings/appearance.

Comment (erikj79) [reply make/modules/java.base/gensrc/GensrcBuffer.gmk:162]: You are right, thanks for that link!

**Comment by xxDark** [comment]
Hello, this seemingly broke the build on Windows x64.
VarHandleGuards class does not get generated.
```
                             ^
f:\openjdk\src\java.base\share\classes\java\lang\invoke\MethodHandleNatives.java:558: error: cannot find symbol
                    VarHandleGuards.class, getVarHandleGuardMethodName(guardType),
                    ^
  symbol:   class VarHandleGuards
  location: class MethodHandleNatives
f:\openjdk\src\java.base\share\classes\java\lang\invoke\MethodHandleNatives.java:562: error: cannot find symbol
                                                           VarHandleGuards.class, LM_TRUSTED);
                                                           ^
  symbol:   class VarHandleGuards
  location: class MethodHandleNatives
f:\openjdk\src\java.base\share\classes\java\lang\invoke\VarHandle.java:2249: error: cannot find symbol
        UNSAFE.ensureClassInitialized(VarHandleGuards.class)
        
```
Reverting this commit fixed the issue.
The setup to configure the build was as follows:
```
set JAVA_HOME=D:\jdks\temurin-24.0.32
d:\MSV2019\VC\Auxiliary\Build\vcvars64.bat
d:\cygwin64\Cygwin.bat
cd /cygdrive/f/openjdk
bash configure
make java.base
```

```
$ make clean java.base
Building targets 'clean java.base' in configuration 'windows-x86_64-server-release'
Cleaning hotspot build artifacts ... done
Cleaning jdk build artifacts ... done
Cleaning bootcycle-build build artifacts ... done
Cleaning test-results build artifacts ... done
Cleaning test-support build artifacts ... done
Cleaning test build artifacts ... done
Cleaning buildtools build artifacts ... done
Cleaning support build artifacts ... done
Cleaning support/images build artifacts ... done
Cleaning images build artifacts ... done
Cleaning make-support build artifacts ... done
Cleaning test-make build artifacts ... done
Cleaning bundles build artifacts ... done
Cleaning buildjdk build artifacts ... done
Cleaned all build artifacts.
Compiling up to 1 files for BUILD_TOOLS_HOTSPOT
Compiling up to 9 files for BUILD_TOOLS_LANGTOOLS
Generating classes for compiler.properties launcher.properties
Compiling 17 properties into resource bundles for jdk.javadoc
Generating FlagsEnum
Compiling 19 properties into resource bundles for jdk.compiler
Compiling up to 136 files for BUILD_java.compiler.interim
Compiling up to 360 files for BUILD_jdk.compiler.interim
Compiling up to 145 files for BUILD_jdk.internal.md.interim
Compiling up to 213 files for BUILD_jdk.javadoc.interim
Compiling up to 17 files for BUILD_JAVAC_SERVER
Compiling up to 190 files for BUILD_TOOLS_JDK
Compiling up to 2 files for COMPILE_DEPEND
Compiling up to 2 files for BUILD_BREAKITERATOR_BASE
Compiling up to 2 files for BUILD_BREAKITERATOR_LD
SocketOptionRegistry.java.template
d:\msvwin10kit\include\10.0.19041.0\um\winbase.h(9531): warning C5105: macro expansion producing 'defined' has undefined behavior
Compiling 11 properties into resource bundles for java.base
Compiling 3 properties into resource bundles for java.base
Compiling 22 properties into resource bundles for java.base
Compiling 11 properties into resource bundles for java.base
Compiling up to 3366 files for java.base
Creating hotspot/variant-server/tools/adlc/adlc.exe from 13 file(s)
Compiling up to 2 files for BUILD_JVMTI_TOOLS
Creating support/modules_libs/java.base/server/jvm.dll from 1223 file(s)
f:\jdk\src\java.base\share\classes\java\lang\invoke\MethodHandleNatives.java:558: error: cannot find symbol
                    VarHandleGuards.class, getVarHandleGuardMethodName(guardType),
                    ^
  symbol:   class VarHandleGuards
  location: class MethodHandleNatives
f:\jdk\src\java.base\share\classes\java\lang\invoke\MethodHandleNatives.java:562: error: cannot find symbol
                                                           VarHandleGuards.class, LM_TRUSTED);
                                                           ^
  symbol:   class VarHandleGuards
  location: class MethodHandleNatives
f:\jdk\src\java.base\share\classes\java\lang\invoke\VarHandle.java:2249: error: cannot find symbol
        UNSAFE.ensureClassInitialized(VarHandleGuards.class);
                                      ^
  symbol:   class VarHandleGuards
  location: class VarHandle
3 errors
make[3]: *** [CompileJavaModules.gmk:102: /cygdrive/f/jdk/build/windows-x86_64-server-release/jdk/modules/java.base/_the.java.base_batch] Error 1
make[2]: *** [make/Main.gmk:182: java.base-java] Error 2
make[2]: *** Waiting for unfinished jobs....
```

**Comment by liach** [comment]
This patch removed the `VARHANDLES_GENSRC_DIR` variable used by VarHandleGuards generation. I think it can be addressed by a hot fix.

**Comment by AlanBateman** [comment]
> This patch removed the `VARHANDLES_GENSRC_DIR` variable used by VarHandleGuards generation. I think it can be addressed by a hot fix.

I think the change needs to backed out and the differences with line numbers checked to see what impact it will have on stack traces and mapping it back to the sources in the template files.
