### PR TITLE
8264918: [JVMCI] getVtableIndexForInterfaceMethod doesn't check that type and method are related

### PR DESCRIPTION
**Pull request by iwanowww**
getVtableIndexForInterfaceMethod should reject the case when a resolved class doesn't implement the holder interface.

Testing:
- [x] hs-tier1 - hs-tier4

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8264918](https://bugs.openjdk.java.net/browse/JDK-8264918): [JVMCI] getVtableIndexForInterfaceMethod doesn't check that type and method are related

### Reviewers
 * [Vladimir Kozlov](https://openjdk.java.net/census#kvn) (@vnkozlov - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/3396/head:pull/3396` \
`$ git checkout pull/3396`

Update a local copy of the PR: \
`$ git checkout pull/3396` \
`$ git pull https://git.openjdk.java.net/jdk pull/3396/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 3396`

View PR using the GUI difftool: \
`$ git pr show -t 3396`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/3396.diff">https://git.openjdk.java.net/jdk/pull/3396.diff</a>

</details>

### CODE REVIEW

**Review by vnkozlov — APPROVED** [review]
Good.
It needs review from Graal team.

**Comment by dougxc** [comment]
The changes look good to me.
How did you discover this problem? If the detail is in https://bugs.openjdk.java.net/browse/JDK-8264918, I can wait until the JBS server comes back up.

**Comment by iwanowww** [comment]
Thanks for the reviews, Vladimir and Doug.

It was discovered by a new assert introduced in #3346.

**Comment by dougxc** [comment]
Looking into https://bugs.openjdk.java.net/browse/JDK-8265689, I see that it's due to this PR missing these changes:
```
diff --git a/src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.hotspot/src/jdk/vm/ci/hotspot/CompilerToVM.java b/src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.hotspot/src/jdk/vm/ci/hotspot/CompilerToVM.java
index faf3cec709..945ec7ba1a 100644
--- a/src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.hotspot/src/jdk/vm/ci/hotspot/CompilerToVM.java
+++ b/src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.hotspot/src/jdk/vm/ci/hotspot/CompilerToVM.java
@@ -590,8 +590,9 @@ final class CompilerToVM {
      * {@link HotSpotVMConfig#invalidVtableIndex} if {@code method} is not in {@code type}'s
      * v-table.
      *
-     * @throws InternalError if {@code type} is an interface or {@code method} is not held by an
-     *             interface or class represented by {@code type} is not initialized
+     * @throws InternalError if {@code type} is an interface, {@code method} is not defined by an
+     *             interface, {@code type} does not implement the interface defining {@code method}
+     *             or class represented by {@code type} is not initialized
      */
     native int getVtableIndexForInterfaceMethod(HotSpotResolvedObjectTypeImpl type, HotSpotResolvedJavaMethodImpl method);
 
diff --git a/src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.hotspot/src/jdk/vm/ci/hotspot/HotSpotResolvedJavaMethodImpl.java b/src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.hotspot/src/jdk/vm/ci/hotspot/HotSpotResolvedJavaMethodImpl.java
index d494679aff..41dab25d0e 100644
--- a/src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.hotspot/src/jdk/vm/ci/hotspot/HotSpotResolvedJavaMethodImpl.java
+++ b/src/jdk.internal.vm.ci/share/classes/jdk.vm.ci.hotspot/src/jdk/vm/ci/hotspot/HotSpotResolvedJavaMethodImpl.java
@@ -677,7 +677,7 @@ final class HotSpotResolvedJavaMethodImpl extends HotSpotMethod implements HotSp
             return config().invalidVtableIndex;
         }
         if (holder.isInterface()) {
-            if (resolved.isInterface() || !resolved.isLinked()) {
+            if (resolved.isInterface() || !resolved.isLinked() || !getDeclaringClass().isAssignableFrom(resolved)) {
                 return config().invalidVtableIndex;
             }
             return getVtableIndexForInterfaceMethod(resolved);
```

@iwanowww would you mind taking JDK-8265689 and using it to apply these missing changes?
