### PR TITLE
JDK-8312392: ARM32 build broken since 8311035

### PR DESCRIPTION
**Pull request by tstuefe**
Trivial fix.

```
/shared/projects/openjdk/jdk-jdk/source/src/hotspot/share/cds/metaspaceShared.cpp:1256: error: undefined reference to 'CompressedKlassPointers::is_valid_base(unsigned char*)'
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8312392](https://bugs.openjdk.org/browse/JDK-8312392): ARM32 build broken since 8311035 (**Bug** - P4)

### Reviewers
 * [Aleksey Shipilev](https://openjdk.org/census#shade) (@shipilev - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/14934/head:pull/14934` \
`$ git checkout pull/14934`

Update a local copy of the PR: \
`$ git checkout pull/14934` \
`$ git pull https://git.openjdk.org/jdk.git pull/14934/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 14934`

View PR using the GUI difftool: \
`$ git pr show -t 14934`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/14934.diff">https://git.openjdk.org/jdk/pull/14934.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/14934#issuecomment-1642114039)

### CODE REVIEW

**Review by shipilev — APPROVED** [review]

**Comment by tstuefe** [comment]
Thanks @shipilev !

Trivial but important, so I'll integrate.

/integrate

**Comment by tstuefe** [comment]
Thanks @shipilev !

/integrate
