### PR TITLE
8333326: Linux Alpine build fails after 8302744

### PR DESCRIPTION
**Pull request by MBaesken**
we run into a basename related build issue on Alpine Linux

basename related issue :
/priv/jenkins/client-home/workspace/openjdk-jdk-dev-linux_alpine_x86_64-opt/jdk/test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp: In member function 'virtual void cgroupTest_read_numerical_key_value_success_cases_Test::TestBody()':
/priv/jenkins/client-home/workspace/openjdk-jdk-dev-linux_alpine_x86_64-opt/jdk/test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp:139:19: error: 'basename' was not declared in this scope; did you mean 'rename'?
  139 | const char* b = basename(test_file);
      | ^~~~~~~~
      | rename

Additionally giving a 'const char*'  to basename results in a warning as error because basename interface gets a char* .

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8333326](https://bugs.openjdk.org/browse/JDK-8333326): Linux Alpine build fails after 8302744 (**Bug** - P3)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**) ⚠️ Review applies to [834b68f9](https://git.openjdk.org/jdk/pull/19497/files/834b68f979e3acc417f9f1143b87c465db6661d8)
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [fabfcd22](https://git.openjdk.org/jdk/pull/19497/files/fabfcd22013adacab3dcd9c3c81c8d0606ecddbe)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/19497/head:pull/19497` \
`$ git checkout pull/19497`

Update a local copy of the PR: \
`$ git checkout pull/19497` \
`$ git pull https://git.openjdk.org/jdk.git pull/19497/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19497`

View PR using the GUI difftool: \
`$ git pr show -t 19497`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/19497.diff">https://git.openjdk.org/jdk/pull/19497.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/19497#issuecomment-2141734466)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]

**Review by RealCLanger — APPROVED** [review]

File: test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp [hunk 1]
```diff
@@ -34,6 +34,10 @@
 
 #include <stdio.h>
 
+#ifdef MUSL_LIBC
+#include <libgen.h> // for basename
+#endif
```
Comment (dholmes-ora) [inline test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp:39]: Does glibc provide its own definition of `basename`? From what I can see on Linux `man -s 3 basename` shows:
```
SYNOPSIS
       #include <libgen.h>
..
       char *basename(char *path);
```
which seems to eb same as what you now have for MUSL-C. ???

Comment (jerboaa) [reply test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp:39]: Good point. The man page also has:

```
VERSIONS
       There are two different versions of basename() - the POSIX version  de‐
       scribed above, and the GNU version, which one gets after

               #define _GNU_SOURCE         /* See feature_test_macros(7) */
               #include <string.h>

       The  GNU  version  never  modifies  its argument, and returns the empty
       string when path has a trailing slash, and in particular also  when  it
       is "/".  There is no GNU version of dirname().

       With glibc, one gets the POSIX version of basename() when <libgen.h> is
       included, and the GNU version otherwise.
```

So it sounds like we use the GNU version when `glibc` is being used.

**Review by tstuefe — COMMENTED** [review]
I think this is fine as a fix, but please add a comment somewhere (best before temp_file) that we rely on temp_file returning *modifiable memory* in *resource area*. 

I was confused as to why we don't need ResourceMarks. Does the gtest launcher create ResourceMarks before invoking the TEST functions? May be better to add them to the TEST functions.

Alternatively, we could also modify temp_file to return c heap memory, and then explicitly free that at the end of each test function. Both changes are simple, but the latter may be less brittle (e.g. we can test this stuff even if RA are broken) and easier to immediately grasp.

File: test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp (hunk 1 above)
Comment (tstuefe) [reply test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp:39]: Yeah. Since we want to be libc agnostic, we should use the POSIX variant, though..

Comment (dholmes-ora) [reply test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp:39]: Thanks @jerboaa I obviously completely missed that. :(

But as per Thomas's comment we should be using the Posix function not glibc version. Then we would not need to specialize for Musl-C.

Comment (MBaesken) [reply test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp:39]: So should I remove the ifdef MUSL_LIBC  ?
I considered this but was not sure because  it might change more than just fixing the Alpine build.

Comment (tstuefe) [reply test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp:39]: Yes, you can remove it. Both libc's actually require libgen.h for basename.

**Comment by MBaesken** [comment]
I removed the MUSL_LIBC ifdef and added comments.

File: test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp [hunk 2]
```diff
@@ -34,9 +34,8 @@
 
 #include <stdio.h>
 
-#ifdef MUSL_LIBC
-#include <libgen.h> // for basename
-#endif
+// for basename, needed for Alpine
```
Comment (jerboaa) [inline test/hotspot/gtest/runtime/test_cgroupSubsystem_linux.cpp:37]: Nit: Drop `needed for Alpine`. We include `libgen.h` unconditionally so that the posix version of `basename` is being used (rather than the GNU version).

**Review by tstuefe — APPROVED** [review]
Good for me, if you fix Severins remark. Thank you for fixing this.

**Review by jerboaa — APPROVED** [review]

**Comment by MBaesken** [comment]
Thanks for the reviews !

/integrate
