### PR TITLE
8295795: hsdis does not build with binutils 2.39+

### PR DESCRIPTION
**Pull request by shipilev**
Fails like this:

```
$ sh ./configure --with-boot-jdk=jdk19u-ea --with-hsdis=binutils --with-binutils-src=binutils-2.39
$ make clean build-hsdis

=== Output from failing command(s) repeated here ===
* For target support_hsdis_hsdis-binutils.o:
/home/shade/trunks/jdk/src/utils/hsdis/binutils/hsdis-binutils.c: In function 'init_disassemble_info_from_bfd':
/home/shade/trunks/jdk/src/utils/hsdis/binutils/hsdis-binutils.c:564:3: error: too few arguments to function 'init_disassemble_info'
  564 | init_disassemble_info(dinfo, stream, fprintf_func);
      | ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/shade/trunks/jdk/src/utils/hsdis/binutils/hsdis-binutils.c:62:
/home/shade/trunks/jdk/binutils-2.39/include/dis-asm.h:472:13: note: declared here
  472 | extern void init_disassemble_info (struct disassemble_info *dinfo, void *stream,
      | ^~~~~~~~~~~~~~~~~~~~~
```

Additional testing:
 - [x] Linux x86_64 build with binutils 2.38 (still works)
 - [x] Linux x86_64 build with binutils 2.39 (now works)
 - [ ] JMH -prof perfasm with binutils-2.39-built hsdis

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295795](https://bugs.openjdk.org/browse/JDK-8295795): hsdis does not build with binutils 2.39+

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk.git pull/10817/head:pull/10817` \
`$ git checkout pull/10817`

Update a local copy of the PR: \
`$ git checkout pull/10817` \
`$ git pull https://git.openjdk.org/jdk.git pull/10817/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10817`

View PR using the GUI difftool: \
`$ git pr show -t 10817`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk/pull/10817.diff">https://git.openjdk.org/jdk/pull/10817.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk/pull/10817#issuecomment-1287128647)

### CODE REVIEW

**Comment by shipilev** [comment]
Oh no, this does not work, hsdis SEGVs. Let me try and fix it.

**Comment by luhenry** [comment]
@shipilev would you be ok for me to take a look?

**Comment by shipilev** [comment]
> @shipilev would you be ok for me to take a look?

Yes, be my guest.  You'll embark on a wonderful journey on how it is nearly impossible to write complex and compliant code with va_args :)

**Comment by luhenry** [comment]
I was thinking one of the required change is to add a variant to `decode_instructions_virtual` that accepts `va_list` instead of `...`. That plus add an enum for the type of node (pretty much mapping `enum disassembler_style`). Am I missing something?

**Comment by shipilev** [comment]
> Edit: Issue arises because hsdis needs to support older versions of hotspot which expect a `...` argument. Other than breaking compatibility of newer hsdis for older JVMs, I don't know how to keep the compatibility both ways.

Yes, that was my roadblock as well. I cannot yet see the fix that fixes it for all binutils versions. This what makes the BFD API change so awkward...

**Comment by luhenry** [comment]
Let me raise the question on the mailing list. Maybe we would need to have a non backward or forward compatible hsdis.

**Review by theRealAph — APPROVED** [review]

**Comment by theRealAph** [comment]
So I'm trying to revert my mistaken approval.

**Comment by erikj79** [comment]
> So I'm trying to revert my mistaken approval.

Do another review with "Request changes" to invalidate your previous approval.

**Comment by magicus** [comment]
Maybe introduce a versioning protocol as part of the hsdis API? That way at the very least hsdis can tell the user in a polite way that the current JVM is too old to be supported, instead of crashing with unhelpful error messages?

**Comment by magicus** [comment]
I started on a journey that I unfortunately never got around to finish, with using the license-unencumbered capstone hsdis implementation, and include that as default when building the JVM.

Apparently there is still need for the binutils hsdis, which I guess is due to limitations in the capstone version compared to binutils. (?) Otherwise binutils is just a plain pain to work with from the JDK perspective, due to the incompatible license involved.

Given that the capstone hsdis version can be made to match the binutil version in functionality, I think it would be a much saner path forward to focus on that implementation, and just bundle it with the JVM.

**Comment by shipilev** [comment]
> Given that the capstone hsdis version can be made to match the binutil version in functionality, I think it would be a much saner path forward to focus on that implementation, and just bundle it with the JVM.

I wish Capstone was on-par with binutils, but it seems to be not, architecture support wise. For example, I don't see RISC-V support in Capstone. I think binutils supports basically all arches the GNU toolchains support, which allows building hsdis for all those arches, e.g. https://builds.shipilev.net/hsdis/ :)

**Comment by magicus** [comment]
RISC-V in Capstone seems to be in a bit of a limbo. The welcome page says:

> Highlight features
>    Multi-architectures: [...] , RISCV, [...] ([details](http://www.capstone-engine.org/arch.html)).

but the "details" page does not mention RISC-V.

Some digging indicate that RISC-V has been present for 2 years in their `next` branch:  https://github.com/capstone-engine/capstone/blob/next/include/capstone/riscv.h

Is there any other platforms apart from RISC-V missing?

My understanding from previous bouts of this discussion is that binutils format strings differently from other disassemblers, and is more or less "clever" in resolving some constructs. If this is a blocker, I think there are some possibilities to tweak some knobs on Capstone to make it appear more like binutils.

If upgrading binutils to 2.39+ is a dead end, or at least requires more intrusive changes, I think it might be just as worthwhile in spending that time trying to make Capstone a full-fledged replacement for binutils.

**Comment by luhenry** [comment]
LLVM can be a good replacement for binutils in these newer platforms. RISC-V support in LLVM for example is on-par with GCC's.

I haven't looked what's the license for LLVM and whether it's compatible with the OpenJDK's, but I would still see the need to support more than 1 backend for hsdis for new/esoteric platforms (Windows-AArch64 being the reason to do LLVM backend in the first place).

**Comment by magicus** [comment]
So what do we do with this? 
* Declare in building.md that we only support binutils prior to 2.39? 
* Sacrifice backwards compatibility if we build with binutils 2.39 or above? 
* Is there a third option?

**Comment by luhenry** [comment]
I'd go with sacrificing backward compatibility for multiple reasons:
1. It's an internal tool mostly targeted at Hotspot contributors (does this assumption holds true in your experience?). Some documentation and communication on the mailing list would help in the transition
2. Despite being annoying to build and distribute, binutils is still a reference implementation for tooling and has a support for a wide range of platforms.

I haven't looked how much breaking this compatibility is going to impact other hsdis implementations though (as-in will it require a change of API in hotspot <-> hsdis as well as hsdis <-> binutils/llvm/capstone

**Comment by magicus** [comment]
Would the lack of backwards compatibility be helped by adding some kind of versioning coherence check to the hotspot/hsdis interface? 

I guess it will not help in this particular case -- as I understand it, the problem is that if we modify hsdis-binutils to support binutils 2.39, it will not be usable in older Hotspot versions. So it will not help if newer hsdis dlls flag themselves as "newer", since the older Hotspots will not be looking for that.

But it might help with future transitions, if we ever expect any such.

**Comment by magicus** [comment]
What happens if we adopt the hsdis interface to match the new binutils, and we try to:
a) load a new hsdis into an old hotspot, or
b) load an old hsdis into a new hotspot?

Are we bound to just have incomprehensible crashes, or can we employ some tricks to at least be able to present an understandable error message to the user?

I could live with breaking compatibility if we output something like "This version of hsdis is too old" or "This version of Hotspot is too old". Creating a random and hard-to-debug crash dump due to method signature mismatches makes me much less keen on going down that route.

Otherwise I agree with you: I think that hsdis is usually used by a few select Hotspot developers, and that they hopefully build hsdis and hotspot together. But I also know there are a lot of guides out there in the wild, suggesting that you put hsdis.so somewhere on your lib path. I have no clue how common this is, but if people have done that, we can cause a lot of problem if this causes hard crashes with no good description with the problem.

**Comment by theRealAph** [comment]
>     [ hsdis is ] an internal tool mostly targeted at Hotspot contributors (does this assumption holds true in your experience?). 

I very strongly disagree. It's a tool increasingly used by performance engineers to gain real insights in performance.
