### PR TITLE
8155701: The compiler fails with an AssertionError: typeSig ERROR

### PR DESCRIPTION
**Pull request by sadayapalam**
Make sure javac issues suitable diagnostics for types not found in the class path

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8155701](https://bugs.openjdk.java.net/browse/JDK-8155701): The compiler fails with an AssertionError: typeSig ERROR

### Reviewers
 * [Vicente Romero](https://openjdk.java.net/census#vromero) (@vicente-romero-oracle - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk pull/8414/head:pull/8414` \
`$ git checkout pull/8414`

Update a local copy of the PR: \
`$ git checkout pull/8414` \
`$ git pull https://git.openjdk.java.net/jdk pull/8414/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 8414`

View PR using the GUI difftool: \
`$ git pr show -t 8414`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk/pull/8414.diff">https://git.openjdk.java.net/jdk/pull/8414.diff</a>

</details>

### CODE REVIEW

**Comment by sadayapalam** [comment]
Notes for the reviewer(s):

Consider: 

Class Foo from Foo.java refers to an annotation type @edu.umd.cs.findbugs.annotations.SuppressWarnings properly found on the class path. Foo.java is well formed and is compiled properly into Foo.class

Class Bar from Bar.java compiled separately refers to both class Foo and the annotation @edu.umd.cs.findbugs.annotations.SuppressWarnings BUT has only Foo.class on its class path.

While compiling Bar.java, the reference to Foo causes the class file Foo.class to be read in. The class Foo is found to refer to the annotation type @edu.umd.cs.findbugs.annotations.SuppressWarnings which is not on the current class path and so results in a CompletionFailure. This completion failure is not surfaced (see com.sun.tools.javac.jvm.ClassReader.AnnotationDeproxy#findAccessMethod) as an error - a lint diagnostics get issued if line mode includes class file sanity checks - instead we simply tag the type of the ClassSymbol corresponding to  @edu.umd.cs.findbugs.annotations.SuppressWarnings  as an ErrorType.

Subsequently when we look up the type @edu.umd.cs.findbugs.annotations.SuppressWarnings when Bar.java itself references it, we end up retrieving this stub symbol from the symbol table. 

The fact that @edu.umd.cs.findbugs.annotations.SuppressWarnings  is not on the class path while compiling Bar.java that references this missing type should result in a compilation error for the type not found. Instead we find the stub symbol, not recognize that as a place holder for a missing type and proceed further in the compilation pipeline.

This results in an assertion failure during code generation phase - which should never have been entered in the first place.

The fix is to recognize this scenario and return a typeNotFound error symbol rather than the stub symbol

**Comment by sadayapalam** [comment]
Thanks for the review, Vicente!
