### PR TITLE
8253375: OSX build fails with Xcode 12.0 (12A7209)

### PR DESCRIPTION
**Pull request by phohensee**
Please review this small patch to enable the OSX build using Xcode 12.0.

Thanks,
Paul

/issue add JDK-8253375
/summary Replace double array with short array in AdapterHandlerLibrary::create_native_wrapper, add parens around ?: in CSystemColors:getColor

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8253375](https://bugs.openjdk.java.net/browse/JDK-8253375): OSX build fails with Xcode 12.0 (12A7209)

### Reviewers
 * [Phil Race](https://openjdk.java.net/census#prr) (@prrace - **Reviewer**) ⚠️ Review applies to 5db5edc2a71343b4e9738264e3387c928375378f
 * [Kim Barrett](https://openjdk.java.net/census#kbarrett) (@kimbarrett - **Reviewer**)
 * [Lutz Schmidt](https://openjdk.java.net/census#lucy) (@RealLucy - **Reviewer**)

### Download
`$ git fetch https://git.openjdk.java.net/jdk pull/348/head:pull/348`
`$ git checkout pull/348`

### CODE REVIEW

**Review by prrace — APPROVED** [review]
The awt change looks fine although it would be nice if you could paste the compiler 
error message into the bug report, since I'd like to see the compiler's reason why this is ambiguous today and not before - assuming that is the issue.

File: src/hotspot/share/runtime/sharedRuntime.cpp [hunk 1]
```diff
@@ -2848,7 +2848,7 @@ void AdapterHandlerLibrary::create_native_wrapper(const methodHandle& method) {
     BufferBlob*  buf = buffer_blob(); // the temporary code buffer in CodeCache
     if (buf != NULL) {
       CodeBuffer buffer(buf);
-      double locs_buf[20];
+      short locs_buf[80];
```
Comment (dholmes-ora) [inline src/hotspot/share/runtime/sharedRuntime.cpp:2851]: This code is just weird. Why is the buf array not declared to be the desired type? If the compiler rejects double because it isn't relocInfo* then why does it accept short? And if it accepts short will it accept int or long long or int64_t? Using int64_t would be a clearer change. Though semantically this code is awful. :( Should it be intptr_t ?

**Review by dholmes-ora — CHANGES_REQUESTED** [review]

**Review by kimbarrett — CHANGES_REQUESTED** [review]
No, don't do this.  In the original, double is used to obtain the desired
alignmnent.  Changing the element type to short reduces the alignment
requirement for the variable.  initialize_shared_locs will then adjust the
alignment, potentially shrinking the effective array size.  So this is a
real change that I think shouldn't be made.

I think changing the declaration for locs_buf to any of the following gives
equivalent behavior to the current code. I don't know whether any of them
will trigger the new clang warning though. I don't have access to that
version right now, and the documentation for the warning is useless (like so
much of clang's warning options documentation).

(1) alignas(double) char locs_buf[20 * sizeof(double)];
(but alignas is not yet in the "permitted features" list in the Style Guide:
https://bugs.openjdk.java.net/browse/JDK-8252584)

(2) union { char locs_buf[20 * sizeof(double)]; double align; };

(3) std::aligned_storage_t<20 * sizeof(double)> locs_buf;
and change (relocInfo*)locs_buf => (relocInfo*)&locs_buf
and #include <type_traits>
This has the benefit of being explicit that we're just stack allocating a
block of storage.

I'll make a wild guess that (1) and (2) will still warn, though char arrays
are somewhat special in the language so maybe they won't.  I'm pretty sure
(3) should do the trick.

File: src/java.desktop/macosx/native/libawt_lwawt/awt/CSystemColors.m [hunk 2]
```diff
@@ -126,7 +126,7 @@ + (void)reloadColors {
 + (NSColor*)getColor:(NSUInteger)colorIndex useAppleColor:(BOOL)useAppleColor {
     NSColor* result = nil;
 
-    if (colorIndex < (useAppleColor) ? sun_lwawt_macosx_LWCToolkit_NUM_APPLE_COLORS : java_awt_SystemColor_NUM_COLORS) {
+    if (colorIndex < ((useAppleColor) ? sun_lwawt_macosx_LWCToolkit_NUM_APPLE_COLORS : java_awt_SystemColor_NUM_COLORS)) {
```
Comment (kimbarrett) [inline src/java.desktop/macosx/native/libawt_lwawt/awt/CSystemColors.m:129]: This looks like a plain old bug fix, nothing really to do with the compiler upgrade.  The new compiler presumably just has a new warning that brought attention to the problem.  As such, I don't think it belongs in a PR that's about issues related to the compiler upgrade.  Someone might want to backport just this fix, for example.

**Comment by RealLucy** [comment]
I checked Kim Barrett's proposals (1) and (2) on my machine (MacOS 10.15, Xcode 12.0). Both proposals make the warning go away. 

Another note, actually, it's more like a question:
Has anyone had an eye on what happens in initialize_shared_locs(relocInfo* buf, int length)? To my understanding, "buf", which is passed in as "locs_buf", is stored into CodeBuffer fields. Is that a good idea? "locs_buf" points into the stack. This pointer becomes invalid at the end of the "locs_buf" scope. Did I get something wrong here?

File: src/java.desktop/macosx/native/libawt_lwawt/awt/CSystemColors.m (hunk 2 above)
Comment (MBaesken) [reply src/java.desktop/macosx/native/libawt_lwawt/awt/CSystemColors.m:129]: Hello  Kim, Paul -  so should we open a separate bug for the src/java.desktop/macosx/native/libawt_lwawt/awt/CSystemColors.m issue because it might be a general  problem just uncovered by the new compiler ?
Paul , do you want to do this ? Or should I open a bug and post a separate change for the useAppleColor check in CSystemColors.m ?

File: src/hotspot/share/runtime/sharedRuntime.cpp (hunk 1 above)
Comment (MBaesken) [reply src/hotspot/share/runtime/sharedRuntime.cpp:2851]: Currently we have in the existing code  various kind of buffers passed into initialize_shared_locs that compile nicely on all supported compilers and on Xcode 12 as well ,see

c1_Compilation.cpp

326  char* locs_buffer = NEW_RESOURCE_ARRAY(char, locs_buffer_size);
327  code->insts()->initialize_shared_locs((relocInfo*)locs_buffer,

sharedRuntime.cpp

2681      CodeBuffer buffer(buf);
2682      short buffer_locs[20];
2683      buffer.insts()->initialize_shared_locs((relocInfo*)buffer_locs,
2684                                             sizeof(buffer_locs)/sizeof(relocInfo));

So probably using short would be consistent to what we do already in the coding at another place (looking into relocInfo it would be probably better  to use unsigned short  or to   typedef  unsigned short in the relocInfo class and use the typedef).

File: src/java.desktop/macosx/native/libawt_lwawt/awt/CSystemColors.m (hunk 2 above)
Comment (MBaesken) [reply src/java.desktop/macosx/native/libawt_lwawt/awt/CSystemColors.m:129]: I created 
https://bugs.openjdk.java.net/browse/JDK-8253791
8253791: Issue with useAppleColor check in CSystemColors.m
for this issue (Kim and Paul are fine to have a separate JBS issue for this)

**Review by kimbarrett — APPROVED** [review]

**Review by RealLucy — CHANGES_REQUESTED** [review]
The proposed (updated) change does _NOT_ compile on my machine (MacOS 10.15.6, Xcode 12.0):

sharedRuntime.cpp:2860:46: error: cannot cast from type 'struct (anonymous struct at sharedRuntime.cpp:2859:7)' to pointer type 'relocInfo *'

You will have to use a union (option (2) as proposed by Kim Barrett far above. I proved that variant compiles on my machine.

**Review by RealLucy — APPROVED** [review]
I just copied the declaration and oversaw that tiny little '&'. With it, sharedRuntime.cpp compiles fine. Sorry for not being careful enough. Reviewed.
